stages:
  - test
  - doc


test-java:
  stage: test

  image: maven

  script:
    - mvn test


build-javadoc:
  stage: doc

  image: maven

  # javadoc path
  artifacts:
    name: "Javadoc"
    paths:
      - target/site

  script:
    # Using the javadoc plugin for maven.
    - mvn javadoc:javadoc
