stages:
  - test
  - doc


test-java:
  stage: test

  image: maven

  script:
    - mvn test

  artifacts:
    paths:
      - target/surefire-reports/*.xml


build-javadoc:
  stage: doc

  image: maven

  # javadoc path
  artifacts:
    name: "Javadoc"
    paths:
      - doc

  script:
    # Using the javadoc plugin for maven.
    - mvn javadoc:javadoc
    - mv target/site/apidocs doc
